const express=require("express"),path=require("path"),Database=require("better-sqlite3"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken");
const app=express(),db=new Database("sky_sparrk.db"),PORT=process.env.PORT||3000,SECRET=process.env.JWT_SECRET||"CHANGE_ME";
app.use(express.json());app.use(express.static(path.join(__dirname,"public")));db.pragma("foreign_keys=ON");
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'student');
CREATE TABLE IF NOT EXISTS tests(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,time_minutes INTEGER NOT NULL,published INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS questions(id INTEGER PRIMARY KEY AUTOINCREMENT,test_id INTEGER NOT NULL,subject TEXT,q TEXT NOT NULL,a TEXT,b TEXT,c TEXT,d TEXT,correct INTEGER NOT NULL,explanation TEXT,FOREIGN KEY(test_id) REFERENCES tests(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS attempts(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,test_id INTEGER NOT NULL,score INTEGER,total INTEGER,accuracy REAL,answers_json TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(test_id) REFERENCES tests(id));`);
function tok(u){return jwt.sign({id:u.id,role:u.role},SECRET,{expiresIn:"7d"})}
function auth(req,res,next){try{req.u=jwt.verify((req.headers.authorization||"").replace("Bearer ",""),SECRET);next()}catch(e){res.status(401).json({error:"Login required"})}}
function adm(req,res,next){if(req.u.role!=="admin")return res.status(403).json({error:"Admin only"});next()}
app.post("/api/register",(req,res)=>{let {name,email,password}=req.body;if(!name||!email||!password||password.length<6)return res.status(400).json({error:"Enter valid details"});try{let x=db.prepare("INSERT INTO users(name,email,password_hash) VALUES(?,?,?)").run(name,email.toLowerCase(),bcrypt.hashSync(password,10)),u=db.prepare("SELECT * FROM users WHERE id=?").get(x.lastInsertRowid);res.json({user:safe(u),token:tok(u)})}catch(e){res.status(400).json({error:"Email already registered"})}});
app.post("/api/login",(req,res)=>{let u=db.prepare("SELECT * FROM users WHERE email=?").get((req.body.email||"").toLowerCase());if(!u||!bcrypt.compareSync(req.body.password||"",u.password_hash))return res.status(401).json({error:"Invalid credentials"});res.json({user:safe(u),token:tok(u)})});
app.post("/api/setup-admin",(req,res)=>{if(req.body.key!==process.env.ADMIN_SETUP_KEY)return res.status(403).json({error:"Invalid setup key"});let {email}=req.body;let u=db.prepare("SELECT * FROM users WHERE email=?").get((email||"").toLowerCase());if(!u)return res.status(404).json({error:"User not found"});db.prepare("UPDATE users SET role='admin' WHERE id=?").run(u.id);u=db.prepare("SELECT * FROM users WHERE id=?").get(u.id);res.json({message:"Admin created",user:safe(u)})});
app.get("/api/tests",auth,(req,res)=>res.json(db.prepare("SELECT id,title,time_minutes FROM tests WHERE published=1 ORDER BY id DESC").all()));
app.get("/api/tests/:id",auth,(req,res)=>{let t=db.prepare("SELECT * FROM tests WHERE id=? AND published=1").get(req.params.id);if(!t)return res.status(404).json({error:"Not found"});t.questions=db.prepare("SELECT id,subject,q,a,b,c,d FROM questions WHERE test_id=? ORDER BY id").all(t.id);res.json(t)});
app.post("/api/attempts",auth,(req,res)=>{let t=db.prepare("SELECT * FROM tests WHERE id=? AND published=1").get(req.body.testId),a=req.body.answers||[];if(!t)return res.status(404).json({error:"Not found"});let q=db.prepare("SELECT correct FROM questions WHERE test_id=? ORDER BY id").all(t.id),score=q.reduce((s,x,i)=>s+(Number(a[i])===x.correct),0),total=q.length,accuracy=total?Math.round(score/total*100):0;db.prepare("INSERT INTO attempts(user_id,test_id,score,total,accuracy,answers_json) VALUES(?,?,?,?,?,?)").run(req.u.id,t.id,score,total,accuracy,JSON.stringify(a));res.json({score,total,accuracy})});
app.get("/api/history",auth,(req,res)=>res.json(db.prepare("SELECT a.*,t.title FROM attempts a JOIN tests t ON t.id=a.test_id WHERE user_id=? ORDER BY a.id DESC").all(req.u.id)));
app.get("/api/leaderboard",auth,(req,res)=>res.json(db.prepare("SELECT u.name,MAX(a.accuracy) accuracy,MAX(a.score) score FROM attempts a JOIN users u ON u.id=a.user_id GROUP BY u.id ORDER BY accuracy DESC,score DESC LIMIT 50").all()));
app.get("/api/admin/stats",auth,adm,(req,res)=>res.json({students:db.prepare("SELECT COUNT(*) n FROM users WHERE role='student'").get().n,tests:db.prepare("SELECT COUNT(*) n FROM tests").get().n,questions:db.prepare("SELECT COUNT(*) n FROM questions").get().n,attempts:db.prepare("SELECT COUNT(*) n FROM attempts").get().n}));
app.get("/api/admin/tests",auth,adm,(req,res)=>res.json(db.prepare("SELECT t.*,COUNT(q.id) question_count FROM tests t LEFT JOIN questions q ON q.test_id=t.id GROUP BY t.id ORDER BY t.id DESC").all()));
app.post("/api/admin/tests",auth,adm,(req,res)=>{let x=db.prepare("INSERT INTO tests(title,time_minutes) VALUES(?,?)").run(req.body.title,Number(req.body.time_minutes)||10);res.json({id:x.lastInsertRowid})});
app.patch("/api/admin/tests/:id",auth,adm,(req,res)=>{db.prepare("UPDATE tests SET published=? WHERE id=?").run(req.body.published?1:0,req.params.id);res.json({ok:true})});
app.post("/api/admin/questions",auth,adm,(req,res)=>{let x=req.body;db.prepare("INSERT INTO questions(test_id,subject,q,a,b,c,d,correct,explanation) VALUES(?,?,?,?,?,?,?,?,?)").run(x.test_id,x.subject||"General",x.q,x.a,x.b,x.c,x.d,Number(x.correct),x.explanation||"");res.json({ok:true})});
app.get("/api/admin/questions/:id",auth,adm,(req,res)=>res.json(db.prepare("SELECT * FROM questions WHERE test_id=? ORDER BY id").all(req.params.id)));
app.delete("/api/admin/questions/:id",auth,adm,(req,res)=>{db.prepare("DELETE FROM questions WHERE id=?").run(req.params.id);res.json({ok:true})});
app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));app.listen(PORT,"0.0.0.0",()=>console.log("Sky Sparrk running on port "+PORT));
